const PROMPT_DATABASE = {
    "ai-001": {
        title: "RIDE",
        videoUrl: "https://youtube.com/shorts/HAlAwqD8jGE", // Ganti dengan link asli
        text: `A relaxed yet high-octane cinematic shot of a man riding a vintage customized classic cafe racer motorcycle through a sprawling, sun-drenched neo-cyberpunk ruin.\n\nThe rider exudes a "casual-cool" vibe, wearing a modish cyberpunk casual outfit: a weathered oversized denim jacket over a technical charcoal hoodie, distressed dark cargo joggers with tactical straps, and fingerless leather gloves.\n\nHis posture is relaxed but focused, one hand confidently on the throttle as he navigates through the desolate city.\n\nEnvironment & Atmosphere:\nA bright, post-apocalyptic urban wasteland under a vast, hazy sky. Skeletal mega-skyscrapers overgrown with digital moss and rusted steel rebar.\n\nTechnical Settings:\nShot on Hasselblad X1D II, 50mm lens at f/1.8. 8K quality, Golden Ratio composition.\n\nReference Face Integration:\nUse provided photo reference. Facial features 100% identical.`
    },
    "ai-002": {
        title: "How To Train Your Dragon",
        videoUrl: "https://youtube.com/shorts/VAF2idTiAe0",
        text: `Ultra-realistic cinematic scene of a man using the provided photo reference, riding a massive black dragon resembling Toothless soaring through the sky above steep rocky sea cliffs.\n\nThe man wears authentic Viking-style armor with thick fur lining and a horned helmet. Expression intense and determined.\n\nEnvironment:\nDramatic coastal cliffs, crashing waves far below, swirling mist and sea spray, golden-hour sky.\n\nCamera:\nDynamic low-angle tracking shot, shallow depth of field, IMAX-level cinematic realism.`
    },
    "ai-003": {
        title: "PINK RANGER",
        videoUrl: "https://youtube.com/shorts/78uT5tR90sA",
        text: `Using the provided photo reference, keep the exact shape, structure, and layout of the vegetable seller rack as seen in the original image:\n\na large rectangular wooden-and-metal rack, multi-level shelves, open wire mesh sides, with plastic bags of vegetables hanging on the sides and rear. Do not redesign the rack shape — maintain its authentic Indonesian mobile vegetable seller form.\n\nTransform the motorcycle itself into a modern sport motorcycle, fully faired, aggressive and aerodynamic, finished in glossy pink color that harmonizes with the overall look.\n\nThe original vegetable rack is carefully modified only at the mounting points, reinforced with custom brackets so it can be securely attached to the rear subframe of a sport bike, without changing the rack’s proportions or visual identity.\n\nThe motorcycle is stationary, stopped on a small Indonesian neighborhood street.\n\nA man is seated on the motorcycle, using the photo reference for body position and scale.\n\nA pink sport helmet is placed on top of the fuel tank, resting naturally with realistic contact shadows.\n\nThe man is holding a smartphone, looking at the screen as if reading a message.\n\nHe is wearing a full Power Ranger Pink costume (helmet off) — iconic pink suit with white diamond pattern, gloves, and boots, clean and vibrant.\n\nThe rack is filled exactly like the reference: spinach, kangkung, sawi, chilies (red and green), tomatoes, onions, herbs, and groceries, stored in shelves and transparent plastic bags hanging on the sides, maintaining the same visual density and randomness as a real Indonesian vegetable seller.\n\nStrong visual contrast between:\n– modern pink sport motorcycle\n– traditional Indonesian vegetable rack unchanged in shape\n– Power Ranger Pink costume\n\nUltra-realistic, natural daylight, sharp textures, cinematic depth of field, grounded Indonesian street atmosphere.`
    },
    "ai-004": {
        title: "BRAIN PROCESSOR PC",
        videoUrl: "https://youtube.com/shorts/ftPcVhgqJvI",
        text: `Ultra-realistic cinematic macro–medium shot of a flat open-air PC case placed on an elegant, clean work desk. The flagship motherboard is mounted horizontally, fully exposed in a low-profile open-air layout.At the exact center sits a brain-shaped processor, hyper-realistic human brain form with deep neural folds, organic matte surface, subtle veins, and natural flesh tones — no glow, no internal light, completely unpowered.Several transparent liquid-cooling tubes are connected directly into the brain processor through clean bio-mechanical connectors embedded naturally between folds. The tubes contain clear, colorless coolant, fully static, with no ARGB, no illumination, no movement, no reflections from LEDs.All PC components are powered off:– No RGB or indicator lights– No illuminated RAM or GPU– Monitor screen completely black and off– No reflections from active displaysSurrounding the processor are high-end RAM modules, GPU, and premium motherboard circuitry, all visible in dark metallic finishes, softly blurred to maintain focus on the brain CPU. Cable management is clean and precise.A man assembling the PC is visible from the side or top-down angle, hands carefully adjusting components near the processor. If his face appears, use photo reference for exact facial accuracy (do not alter eyes, nose, lips, jaw, or hairstyle). He wears a plain white casual t-shirt.Lighting is purely studio and environmental, soft diffused light from above and side, realistic shadows defining depth and texture, no artificial tech glow.Camera angle: slightly elevated top-down three-quarter view, macro lens look (85–100mm), shallow depth of field emphasizing the processor and cooling tubes.Ultra-photorealistic, extreme material accuracy, professional studio photography, clean futuristic-minimal aesthetic, 8K detail.`
    },
	"ai-005": {
        title: "KALUNG PEDAS",
        videoUrl: "https://youtube.com/shorts/-Wae7U81ue8",
        text:`Hyper-realistic portrait of an Indonesian man sitting relaxed at a traditional roadside 'warung' bench, holding a piece of crispy fried snack (gorengan) with a glass of steaming hot black coffee on the wooden table. He is wearing a fashionable loose-fitting beige linen shirt unbuttoned at the top, paired with a high-quality woven black sarong and simple rubber flip-flops.FOCUS ON JEWELRY: He is wearing an extravagant, massive stack of over 10 distinct chili necklaces worn simultaneously. The necklaces cascade down his chest in heavy, voluminous layers, creating a thick, vibrant ruff of textures. The mix includes long shiny red cayenne peppers, twisted green chilies, and dense clusters of orange bird’s-eye chilies, all stringed together. On his wrists, chunky bracelets composed of red shallots with peeling papery skins, garlic cloves, and mixed chilies. On his fingers, large statement rings resembling smooth, matte chicken eggs.The background is a lively afternoon street scene with blurred pedestrians walking by, worn tarpaulins, and tropical sunlight filtering through trees. Shot with a Hasselblad X1D II 50C, 80mm f/1.9 lens to create a creamy bokeh and cinematic depth of field. Golden hour lighting casting warm, dynamic shadows on the face and emphasizing the glossy texture of the massive pile of chilies. Ultra-detailed skin texture, 8k resolution, photorealistic masterpiece, volumetric lighting.[FACE REFERENCE SETTINGS]: Ideally preserve the facial identity from the provided source image. Ensure organic face reconstruction where the skin tone, shadows, and lighting on the face match the warm golden hour environment of the warung. Maintain exact eye shape, nose structure, lip contour, jawline, and head proportions. Modify only the expression to appear relaxed and enjoying the moment, and adjust the head pose slightly to face the camera or the coffee, ensuring seamless integration without a 'pasted-on' look.`
    },
	"ai-006": {
        title: "SUASANA DESA",
        videoUrl: "https://youtube.com/shorts/-t73YGhQyOQ",
        text: `Core Visual Description:Sebuah mahakarya fotografi yang menampilkan pemandangan sungai dangkal yang jernih di pinggir sebuah desa tradisional khas Indonesia. Air sungai mengalir tenang di atas batu-batu kali yang licin, dikelilingi oleh hamparan sawah terasering hijau di latar belakang. Tampak deretan rumah panggung kayu tradisional dengan atap limasan atau joglo yang autentik. Seorang pria (berdasarkan referensi foto) duduk dengan santai di atas batu kali besar di pinggir sungai, mengenakan pakaian kasual modis berupa kemeja tenun modern berlengan pendek dan celana chino katun, memberikan kesan lokal namun elegan. Ia tampak menyentuh air sungai yang bening dengan jemarinya.Technical Photography Settings:Diambil dengan Hasselblad X1D II 50C, lensa 35mm f/1.4, memberikan sudut pandang luas (wide-angle) yang dramatis dengan kedalaman bidang (depth of field) yang memukau. Pencahayaan Golden Hour yang hangat menembus celah-celah pohon kelapa dan bambu, menciptakan efek God rays (Tyndall effect). Komposisi Golden Ratio dengan keseimbangan visual antara elemen air, manusia, dan arsitektur desa.Indonesian Tropical Details:Tekstur ultra-detail pada daun pisang yang mengkilap, rumpun bambu yang rimbun, dan lumut pada bebatuan sungai. Atmosfer pedesaan yang lembap dan sejuk, warna alam yang kaya (hijau zamrud, cokelat kayu tua, dan langit biru keemasan). Resolusi 8k dengan ketajaman tingkat tinggi pada tekstur kayu rumah dan riak air.Face Reference & Integration Settings:[Reference Image Applied] Rekonstruksi Organik Wajah: Integrasi wajah subjek secara natural ke dalam pencahayaan tropis yang hangat, memastikan bayangan pada wajah sesuai dengan arah cahaya matahari sore yang datang dari samping. Karakteristik Wajah Tetap: Menjaga keaslian fitur wajah (mata, hidung, garis rahang, dan bibir) tanpa perubahan identitas dari foto referensi. Ekspresi & Pose: Ekspresi wajah yang tenang, kontemplatif, dan sedikit tersenyum tipis, menyatu sempurna dengan suasana desa yang damai.Final Polish:Cinematic natural lighting, ultra-realistic skin texture, high-fidelity environment, no distortion, professional color grading`
    },
	"ai-007": {
        title: "ON FIRE",
        videoUrl: "https://youtube.com/shorts/VN3AVw6bPpY",
        text: `Ultra-realistic dynamic action shot of a male road cyclist based strictly on the provided reference photo (facial features, body proportions, and identity must remain unchanged), powerfully sprinting uphill on a steep mountain climb. His body leans aggressively forward, jaw clenched, facial expression shows extreme effort and determination, veins visible on neck and arms.He wears a professional road cycling jersey in blue with orange and black accents, tight aerodynamic fit, matching cycling shorts, helmet, and gloves. The road bike is lightweight carbon, gears engaged for climbing, chain under tension, wheels slightly blurred from motion.Low-angle cinematic camera from the front-side, emphasizing the steep incline and raw power. Natural daylight, dramatic contrast, sweat glistening on skin, dust and small gravel subtly kicked up by the tires. Background shows winding mountain road with lush greenery and depth, shallow depth of field, motion blur on surroundings but sharp focus on the cyclist’s face and body.Hyper-realistic textures, realistic lighting, high shutter-speed sports photography feel, cinematic realism, intense athletic energy.`
    }
};
