const PROMPT_DATABASE = {
    "ai-001": {
        title: "RIDE",
        videoUrl: "https://youtube.com/shorts/HAlAwqD8jGE", // Ganti dengan link asli
        text: `A relaxed yet high-octane cinematic shot of a man riding a vintage customized classic cafe racer motorcycle through a sprawling, sun-drenched neo-cyberpunk ruin.\n\nThe rider exudes a "casual-cool" vibe, wearing a modish cyberpunk casual outfit: a weathered oversized denim jacket over a technical charcoal hoodie, distressed dark cargo joggers with tactical straps, and fingerless leather gloves.\n\nHis posture is relaxed but focused, one hand confidently on the throttle as he navigates through the desolate city.\n\nEnvironment & Atmosphere:\nA bright, post-apocalyptic urban wasteland under a vast, hazy sky. Skeletal mega-skyscrapers overgrown with digital moss and rusted steel rebar.\n\nTechnical Settings:\nShot on Hasselblad X1D II, 50mm lens at f/1.8. 8K quality, Golden Ratio composition.\n\nReference Face Integration:\nUse provided photo reference. Facial features 100% identical.`
    },
    "ai-002": {
        title: "How To Train Your Dragon",
        videoUrl: "https://youtube.com/shorts/VAF2idTiAe0",
        text: `Ultra-realistic cinematic scene of a man using the provided photo reference, riding a massive black dragon resembling Toothless soaring through the sky above steep rocky sea cliffs.\n\nThe man wears authentic Viking-style armor with thick fur lining and a horned helmet. Expression intense and determined.\n\nEnvironment:\nDramatic coastal cliffs, crashing waves far below, swirling mist and sea spray, golden-hour sky.\n\nCamera:\nDynamic low-angle tracking shot, shallow depth of field, IMAX-level cinematic realism.`
    },
    "ai-003": {
        title: "PINK RANGER",
        videoUrl: "https://youtube.com/shorts/78uT5tR90sA",
        text: `Using the provided photo reference, keep the exact shape, structure, and layout of the vegetable seller rack as seen in the original image:\n\na large rectangular wooden-and-metal rack, multi-level shelves, open wire mesh sides, with plastic bags of vegetables hanging on the sides and rear. Do not redesign the rack shape — maintain its authentic Indonesian mobile vegetable seller form.\n\nTransform the motorcycle itself into a modern sport motorcycle, fully faired, aggressive and aerodynamic, finished in glossy pink color that harmonizes with the overall look.\n\nThe original vegetable rack is carefully modified only at the mounting points, reinforced with custom brackets so it can be securely attached to the rear subframe of a sport bike, without changing the rack’s proportions or visual identity.\n\nThe motorcycle is stationary, stopped on a small Indonesian neighborhood street.\n\nA man is seated on the motorcycle, using the photo reference for body position and scale.\n\nA pink sport helmet is placed on top of the fuel tank, resting naturally with realistic contact shadows.\n\nThe man is holding a smartphone, looking at the screen as if reading a message.\n\nHe is wearing a full Power Ranger Pink costume (helmet off) — iconic pink suit with white diamond pattern, gloves, and boots, clean and vibrant.\n\nThe rack is filled exactly like the reference: spinach, kangkung, sawi, chilies (red and green), tomatoes, onions, herbs, and groceries, stored in shelves and transparent plastic bags hanging on the sides, maintaining the same visual density and randomness as a real Indonesian vegetable seller.\n\nStrong visual contrast between:\n– modern pink sport motorcycle\n– traditional Indonesian vegetable rack unchanged in shape\n– Power Ranger Pink costume\n\nUltra-realistic, natural daylight, sharp textures, cinematic depth of field, grounded Indonesian street atmosphere.`
    },
    "ai-004": {
        title: "BRAIN PROCESSOR PC",
        videoUrl: "https://youtube.com/shorts/ftPcVhgqJvI",
        text: `Ultra-realistic cinematic macro–medium shot of a flat open-air PC case placed on an elegant, clean work desk. The flagship motherboard is mounted horizontally, fully exposed in a low-profile open-air layout.At the exact center sits a brain-shaped processor, hyper-realistic human brain form with deep neural folds, organic matte surface, subtle veins, and natural flesh tones — no glow, no internal light, completely unpowered.Several transparent liquid-cooling tubes are connected directly into the brain processor through clean bio-mechanical connectors embedded naturally between folds. The tubes contain clear, colorless coolant, fully static, with no ARGB, no illumination, no movement, no reflections from LEDs.All PC components are powered off:– No RGB or indicator lights– No illuminated RAM or GPU– Monitor screen completely black and off– No reflections from active displaysSurrounding the processor are high-end RAM modules, GPU, and premium motherboard circuitry, all visible in dark metallic finishes, softly blurred to maintain focus on the brain CPU. Cable management is clean and precise.A man assembling the PC is visible from the side or top-down angle, hands carefully adjusting components near the processor. If his face appears, use photo reference for exact facial accuracy (do not alter eyes, nose, lips, jaw, or hairstyle). He wears a plain white casual t-shirt.Lighting is purely studio and environmental, soft diffused light from above and side, realistic shadows defining depth and texture, no artificial tech glow.Camera angle: slightly elevated top-down three-quarter view, macro lens look (85–100mm), shallow depth of field emphasizing the processor and cooling tubes.Ultra-photorealistic, extreme material accuracy, professional studio photography, clean futuristic-minimal aesthetic, 8K detail.`
    },
	"ai-005": {
        title: "KALUNG PEDAS",
        videoUrl: "https://youtube.com/shorts/-Wae7U81ue8",
        text:`Hyper-realistic portrait of an Indonesian man sitting relaxed at a traditional roadside 'warung' bench, holding a piece of crispy fried snack (gorengan) with a glass of steaming hot black coffee on the wooden table. He is wearing a fashionable loose-fitting beige linen shirt unbuttoned at the top, paired with a high-quality woven black sarong and simple rubber flip-flops.FOCUS ON JEWELRY: He is wearing an extravagant, massive stack of over 10 distinct chili necklaces worn simultaneously. The necklaces cascade down his chest in heavy, voluminous layers, creating a thick, vibrant ruff of textures. The mix includes long shiny red cayenne peppers, twisted green chilies, and dense clusters of orange bird’s-eye chilies, all stringed together. On his wrists, chunky bracelets composed of red shallots with peeling papery skins, garlic cloves, and mixed chilies. On his fingers, large statement rings resembling smooth, matte chicken eggs.The background is a lively afternoon street scene with blurred pedestrians walking by, worn tarpaulins, and tropical sunlight filtering through trees. Shot with a Hasselblad X1D II 50C, 80mm f/1.9 lens to create a creamy bokeh and cinematic depth of field. Golden hour lighting casting warm, dynamic shadows on the face and emphasizing the glossy texture of the massive pile of chilies. Ultra-detailed skin texture, 8k resolution, photorealistic masterpiece, volumetric lighting.[FACE REFERENCE SETTINGS]: Ideally preserve the facial identity from the provided source image. Ensure organic face reconstruction where the skin tone, shadows, and lighting on the face match the warm golden hour environment of the warung. Maintain exact eye shape, nose structure, lip contour, jawline, and head proportions. Modify only the expression to appear relaxed and enjoying the moment, and adjust the head pose slightly to face the camera or the coffee, ensuring seamless integration without a 'pasted-on' look.`
    },
	"ai-006": {
        title: "SUASANA DESA",
        videoUrl: "https://youtube.com/shorts/-t73YGhQyOQ",
        text: `Core Visual Description:Sebuah mahakarya fotografi yang menampilkan pemandangan sungai dangkal yang jernih di pinggir sebuah desa tradisional khas Indonesia. Air sungai mengalir tenang di atas batu-batu kali yang licin, dikelilingi oleh hamparan sawah terasering hijau di latar belakang. Tampak deretan rumah panggung kayu tradisional dengan atap limasan atau joglo yang autentik. Seorang pria (berdasarkan referensi foto) duduk dengan santai di atas batu kali besar di pinggir sungai, mengenakan pakaian kasual modis berupa kemeja tenun modern berlengan pendek dan celana chino katun, memberikan kesan lokal namun elegan. Ia tampak menyentuh air sungai yang bening dengan jemarinya.Technical Photography Settings:Diambil dengan Hasselblad X1D II 50C, lensa 35mm f/1.4, memberikan sudut pandang luas (wide-angle) yang dramatis dengan kedalaman bidang (depth of field) yang memukau. Pencahayaan Golden Hour yang hangat menembus celah-celah pohon kelapa dan bambu, menciptakan efek God rays (Tyndall effect). Komposisi Golden Ratio dengan keseimbangan visual antara elemen air, manusia, dan arsitektur desa.Indonesian Tropical Details:Tekstur ultra-detail pada daun pisang yang mengkilap, rumpun bambu yang rimbun, dan lumut pada bebatuan sungai. Atmosfer pedesaan yang lembap dan sejuk, warna alam yang kaya (hijau zamrud, cokelat kayu tua, dan langit biru keemasan). Resolusi 8k dengan ketajaman tingkat tinggi pada tekstur kayu rumah dan riak air.Face Reference & Integration Settings:[Reference Image Applied] Rekonstruksi Organik Wajah: Integrasi wajah subjek secara natural ke dalam pencahayaan tropis yang hangat, memastikan bayangan pada wajah sesuai dengan arah cahaya matahari sore yang datang dari samping. Karakteristik Wajah Tetap: Menjaga keaslian fitur wajah (mata, hidung, garis rahang, dan bibir) tanpa perubahan identitas dari foto referensi. Ekspresi & Pose: Ekspresi wajah yang tenang, kontemplatif, dan sedikit tersenyum tipis, menyatu sempurna dengan suasana desa yang damai.Final Polish:Cinematic natural lighting, ultra-realistic skin texture, high-fidelity environment, no distortion, professional color grading`
    },
	"ai-007": {
        title: "ON FIRE",
        videoUrl: "https://youtube.com/shorts/VN3AVw6bPpY",
        text: `Ultra-realistic dynamic action shot of a male road cyclist based strictly on the provided reference photo (facial features, body proportions, and identity must remain unchanged), powerfully sprinting uphill on a steep mountain climb. His body leans aggressively forward, jaw clenched, facial expression shows extreme effort and determination, veins visible on neck and arms.He wears a professional road cycling jersey in blue with orange and black accents, tight aerodynamic fit, matching cycling shorts, helmet, and gloves. The road bike is lightweight carbon, gears engaged for climbing, chain under tension, wheels slightly blurred from motion.Low-angle cinematic camera from the front-side, emphasizing the steep incline and raw power. Natural daylight, dramatic contrast, sweat glistening on skin, dust and small gravel subtly kicked up by the tires. Background shows winding mountain road with lush greenery and depth, shallow depth of field, motion blur on surroundings but sharp focus on the cyclist’s face and body.Hyper-realistic textures, realistic lighting, high shutter-speed sports photography feel, cinematic realism, intense athletic energy.`
    },
	"ai-008": {
        title: "BERTEDUH CARI KEHANGATAN",
        videoUrl: "https://youtube.com/shorts/VN3AVw6bPpY",
        text: `A surreal hyper-realistic medium shot of a male road cyclist sitting composedly on top of a massive, horizontally stacked burning logs (whole tree trunks, not cut firewood) inside a rustic wooden shelter, captured during a heavy morning downpour. The stacked logs’ surfaces are intensely charred and deeply cracked, revealing an internal molten lava-like glow with bright red embers visible through the fissures, while small active flames trace along the log surfaces. Thick vertical plumes of smoke rise upward, colliding and blending with the cold heavy rain and dense morning mist. The subject wears a soaked professional cycling jersey and bib shorts, form-fitting and aerodynamic, clinging to his body due to the rain. Subtle sponsor-style patterns are visible on the jersey fabric. Dramatic steam rises from his body caused by the extreme heat of the burning logs beneath him. He maintains a calm, contemplative expression, as if patiently waiting for the rain to subside, with a slight dynamic head turn as though looking outward beyond the shelter. In the foreground, a road racing bicycle (drop handlebars, thin slick tires, carbon frame), completely drenched by rain, leans clearly against one of the wooden shelter posts. Water droplets cling to the frame, chain, and rims, emphasizing realism and scale. The background reveals a wet rural village road and a lush, dense garden, partially obscured by cold blue-toned morning fog. Rain streaks fall diagonally through the frame, interacting with smoke and steam in layered volumetric depth. foto resolusi tinggi diambil dengan Hasselblad X1D II 50C dengan lensa 50mm f/1.4, komposisi Golden Ratio, low-angle medium shot. Pencahayaan dramatis high-contrast cinematic: strong warm orange underlighting from the glowing logs illuminates the cyclist from below, sharply contrasting with the soft, cool blue ambient light of the rainy morning environment. Ultra-realistic, hyper-detailed textures of wet wood, glowing embers, rain particles, steam, fabric fibers, and carbon bike materials. Shallow depth of field, 8K professional photography, photorealistic masterpiece.`
    },
	"ai-009": {
        title: "MAKAN BESAR",
        videoUrl: "https://youtube.com/shorts/1E4MXBkbtxk",
        text: `Ultra-realistic cinematic photograph of a man using the provided photo reference for facial features and identity, sitting at a large dining table filled with luxurious gourmet dishes (premium meats, traditional Indonesian cuisine, elegant side dishes, fine tableware)He is seated calmly, slightly leaning forward, eyes focused on the plate in front of him, while his right hand is actively taking food from the plate (muluk gesture) in a natural, candid motion.His left hand is raised upward, relaxed but confident, holding a Cuban cigar, with subtle smoke curling upward.Expression is serious, contemplative, composed, conveying authority and indulgence.Outfit: simple dark short-sleeve shirt, realistic fabric texture.Environment: warm indoor dining room, wooden table crowded with dishes, bottled water, plates, bowls, creating a sense of abundance and realism.Lighting: soft cinematic indoor lighting, warm tones, gentle shadows, realistic reflections on plates and glass.Camera: medium shot, eye-level angle, shallow depth of field, natural perspective, high dynamic range.Style: hyper-realistic, documentary-style candid moment, sharp facial detail, natural skin texture, no stylization.Important: Preserve facial structure exactly from the photo reference (eyes, nose, mouth, jawline, hairline).Ultra-detailed, photorealistic, cinematic realism, 8K quality, lifelike atmosphere.`
    },
	"ai-010": {
        title: "MANCING DALAM BARA",
        videoUrl: "https://youtube.com/shorts/1E4MXBkbtxk",
        text: `Seorang pria (berdasarkan foto referensi) duduk dalam pose stabil dan fokus di atas tumpukan besar kayu bakar dan bara api yang menyala di tepi sungai yang liar. Ia mengenakan pakaian bergaya taktis kasual yang modis: rompi taktis kanvas berwarna zaitun gelap di atas hoodie termal abu-abu arang, dipadukan dengan celana kargo hitam teknis yang terlihat kokoh dan sepatu bot hiking kulit yang berlumpur. Kedua tangannya memegang erat joran pancing serat karbon, matanya menatap tajam ke arah air. Tumpukan kayu di bawahnya memancarkan cahaya oranye hangat dari bara yang menyala kecil, dengan asap putih tipis yang mengepul di sekitar sepatu bot dan kakinya, menciptakan kontras suhu visual. Sungai di depannya adalah massa air coklat keruh yang bergolak dengan arus deras dan berbahaya, memantulkan cahaya api dan langit mendung secara kasar dan terdistorsi. Di latar belakang tengah, sebuah pohon tua raksasa yang tumbang mendominasi pemandangan, akar-akarnya yang besar dan berliku menjulur ke udara sementara batangnya yang besar terendam sebagian di dalam arus sungai yang deras. Suasana keseluruhan terasa liar, basah, dan intens, namun subjek tetap tenang di tengah kekacauan elemen alam.Setelan Teknis Fotografi:Gaya: Fotografi petualangan sinematik yang realistik, raw realism.Kamera & Lensa: Diambil dengan kamera medium format Hasselblad X2D 100C menggunakan lensa XCD 55mm f/2.5 V untuk detail tekstur yang luar biasa dan depth of field yang dangkal namun tajam pada subjek.Komposisi: Medium shot dengan komposisi rule of thirds, menggunakan sudut pengambilan gambar rendah (low-angle shot) yang sedikit mendongak ke arah pria untuk menekankan stabilitasnya melawan latar belakang sungai yang turbulen.Pencahayaan: Pencahayaan dramatis campuran (mixed lighting). Cahaya utama adalah moody overcast daylight (cahaya alami mendung yang suram) dari langit, dipadukan dengan warm praktikal light (cahaya oranye hangat) yang kuat dari bara api di bawah, menciptakan rim light hangat pada bagian bawah tubuh, wajah, dan peralatan.Resolusi & Tekstur: Gambar resolusi 8K. Tekstur sangat detail pada serat kain yang basah, kulit yang lapuk, percikan air, kulit kayu yang hangus, dan asap. Film grain halus untuk kesan organik.[INSTRUKSI KHUSUS INTEGRASI WAJAH REFERENSI]Wajah subjek harus direkonstruksi secara organik ke dalam adegan, memastikan integrasi pencahayaan yang sempurna. Cahaya hangat dari bara api di bawah harus menerangi bagian bawah dagu, leher, dan pipi, menciptakan bayangan yang dalam dan realistis yang sesuai dengan bentuk wajah aslinya. Cahaya mendung yang dingin harus menerangi bagian atas kepala. Pertahankan karakteristik identitas wajah asli (bentuk mata, hidung, struktur rahang, bibir) tanpa perubahan apa pun. Ekspresi wajah harus diatur menjadi fokus, intens, dan tenang, menatap ke arah sungai, mencerminkan suasana "berbahaya namun tenang.`
    },
	"ai-011": {
        title: "TAMBAL BAN MOTO GP",
        videoUrl: "https://youtube.com/shorts/bpLwGYNKe7U",
        text: `Seorang pria gunakan foto referensi berada di sebuah lapak tambal ban pinggir jalan khas Indonesia yang berdiri di tepi lintasan MotoGP bagian luar, jauh dari area podium dan paddock. Lapaknya berdiri di atas area berumput liar, dengan sedikit tanah becek, menciptakan suasana benar-benar seperti bengkel pinggir jalan yang tiba-tiba muncul di arena balapan internasional.Lapak dilindungi tenda terpal biru sederhana yang ditopang bambu, tampak sedikit miring karena tertiup angin dari motor balap yang lewat. Peralatan tambal ban lengkap terlihat jelas: ember berisi air sabun, kompresor angin tua yang bergetar, alat congkel ban manual, potongan karet vulkanisir, kuas lem, dan kain lap yang sudah kotor. Semua tampak natural, usang, dan realistis.Pria penambal ban mengenakan kaos putih polos, celana jeans pendek, dan sandal jepit. Ia jongkok fokus menambal ban belakang motor MotoGP yang bocor parah. Ban terlihat kempis menempel tanah, bahkan sedikit penyok di sisi tapaknya. Ia menggunakan air sabun dari ember untuk mengecek kebocoran, memunculkan gelembung kecil yang sangat detail.Hanya satu motor MotoGP yang berhenti di lapak ini: motor dengan fairing karbon, winglet aerodinamis, shock Ohlins emas, dan knalpot titanium yang masih memancarkan heat haze. Motor disandarkan pada paddock stand darurat di atas rumput, sehingga terlihat semakin tidak masuk akal namun tetap ultra-realistis.Sang pembalap MotoGP duduk murung di jok motornya, racing suit penuh sponsor masih dipakai. Helmnya terangkat sebagian, memperlihatkan ekspresi lelah dan putus asa, seolah ia baru saja DNF karena ban bocor dan hanya bisa berharap lapak tambal ban ini dapat ‘menyelamatkan race-nya’. Sarung tangan longgar, bahu merosot, dan posisi tubuh benar-benar menggambarkan kepasrahan.Di latar belakang, meskipun lapak berada jauh di sisi luar lintasan, motor-motor lain tetap melaju kencang, membentuk motion blur dramatis. Marshal terlihat berjaga di kejauhan, tribun tampak jauh di sisi lain trek, dan suara balapan memberikan atmosfer intens.Pencahayaan cinematic, ultra-realistic textures, depth of field kuat yang memisahkan lapak tambal ban di rumput dari kecepatan brutal balapan MotoGP. Perpaduan absurditas ekstrem tetapi disajikan dengan realisme dokumenter yang hidup. @kokosima tersembunyi.`
    },
	"ai-012": {
        title: "DOWNHILL ON FIRE",
        videoUrl: "https://youtube.com/shorts/bpLwGYNKe7U",
        text: `Subject & Action:Ultra-realistic high-octane action sports photography capturing a male road cyclist in mid-sprint up a steep mountain incline. The subject is out of the saddle, body leaning forward in an aggressive aerodynamic posture, showcasing extreme athletic strain. The carbon fiber road bike is swaying laterally under maximum torque, chain fully tensioned. The cyclist wears a high-end, tight-fitting professional cycling jersey in cobalt blue with neon orange and matte black accents, fabric stretching over muscles. Subtle detail: The text "@kokosima" is interwoven into the jersey pattern, barely visible but present.Visual Effects & Atmosphere:Visceral, realistic combustion physics: raging orange-red flames with searing yellow cores erupt directly from the cyclist’s torso and limbs, trailing backward due to high velocity wind resistance. Thick dark smoke and heavy sparks scatter into the air. Heat distortion (shimmer) visibly warps the air around him, blurring parts of the background. The fire casts dynamic, high-contrast rim lighting on his sweat-drenched skin, the metallic bike frame, and the asphalt road texture.Photography & Technical Specs:Shot with Hasselblad X1D II 50C, 80mm f/1.9 lens. Composition follows the Golden Spiral, focusing on the intense facial expression while leading the eye through the trail of fire. Settings: Shutter speed 1/8000s to freeze the sparks and muscle tension, aperture f/2.8 for a shallow depth of field that keeps the subject razor-sharp while rendering the mountain background with heavy, creamy motion blur (bokeh) to emphasize blistering speed. Lighting is a dramatic mix of natural 'Golden Hour' sunlight hitting from the side, clashing with the chaotic, warm glow of the body fire. Low-angle dynamic shot looking up at the cyclist to enhance dominance and power. 8k resolution, raw photo style, hyper-detailed textures.[FACE REFERENCE SETTINGS - STRICT ADHERENCE]Organic Face Reconstruction: The face must be photorealistic and fully integrated into the scene's lighting environment (affected by both the sunlight and the orange glow of the flames). Skin texture must show pores, sweat, and natural imperfections.Identity Preservation: Strictly maintain the facial features from the provided reference photo. Do not alter the eye shape, nose structure, jawline, or head proportions. The identity must remain 100% recognizable.Expression & Pose: Facial expression is modified to show intense physical strain and determination (gritted teeth/clenched jaw, focused eyes), head tilted slightly down but eyes looking forward, consistent with the sprinting posture.`
    },
	"ai-013": {
        title: "COUPLE BW PORTRAIT IMPASTO",
        videoUrl: "https://youtube.com/shorts/NVU8gbb1FV0",
        text: `Fotografi Makro Fine Art: Foto resolusi ultra-tinggi yang diambil dengan kamera Phase One XF IQ4 150MP menggunakan lensa Schneider Kreuznach 120mm f/4 Macro. Fokus tajam pada tekstur fisik cat, memperlihatkan retakan mikro dan tumpukan impasto yang tebal. Pencahayaan galeri sisi (side-lighting) yang dramatis menyapu permukaan lukisan untuk menciptakan bayangan makro di setiap guratan kuas.Deskripsi Karya Seni (Dual Portrait):Sebuah lukisan potret ganda (dua orang) di atas kertas hitam matte bertekstur kasar. Karya ini dibuat secara eksklusif menggunakan cat minyak putih murni (pure white) tanpa campuran warna atau abu-abu. Teknik impasto ekstrem digunakan dengan pisau palet dan kuas kaku, menciptakan relief 3D yang sangat taktil dan ekspresif.Komposisi & Pose:Komposisi close-up dual portrait yang intim mengikuti aturan golden ratio. Kedua subjek berinteraksi secara alami sebagai sahabat dekat, saling condong satu sama lain, berbagi kontak mata, dan senyum spontan yang memancarkan kehangatan, kepercayaan, dan energi ceria.Pencahayaan & Kontras:Gaya Chiaroscuro kontras tinggi yang ekstrem. Wajah, tangan, dan pakaian subjek muncul secara dramatis dari kegelapan ruang negatif hitam pekat. Pencahayaan Rembrandt tunggal memahat kedua wajah secara bersamaan, menciptakan ritme highlight pada tulang pipi dan lipatan kain.Busana & Gaya:Kedua subjek mengenakan pakaian modis, elegan, dan mewah minimalis (seperti blazer atau structured couture) yang dirender hanya melalui sapuan putih tebal yang menekankan bentuk dan siluet, tanpa pola dekoratif.Detail Otentik:Tanda tangan artis " @kokosima " dilukis dengan tangan menggunakan sapuan kuas kursif tipis yang menyatu secara organik ke dalam tekstur cat di sudut bawah karya, menyerupai tanda tangan asli di galeri seni.[Instruksi Khusus Integrasi Wajah Referensi]:Identitas Mutlak: Struktur wajah, proporsi, ekspresi, dan identitas unik dari KEDUA subjek harus tetap identik dengan foto referensi masing-masing.Tanpa Alterasi: Jangan mengubah bentuk mata, hidung, bibir, garis rahang, atau bentuk kepala.Rekonstruksi Organik: Integrasikan fitur wajah referensi ke dalam gaya impasto putih ini dengan memastikan pencahayaan dan bayangan pada wajah selaras dengan sumber cahaya Rembrandt tunggal dalam adegan, mempertahankan karakter wajah namun tetap terlihat sebagai bagian integral dari lukisan fisik yang kasar.`
    },
	"ai-014": {
        title: "BW PORTRAIT IMPASTO",
        videoUrl: "https://youtube.com/shorts/NVU8gbb1FV0",
        text: `Sebuah foto makro resolusi ultra-tinggi dan sinematik dari sebuah karya seni lukis potret kontemporer tingkat museum. Diambil menggunakan kamera medium format Hasselblad H6D-400c MS dengan lensa makro 120mm f/4 untuk menangkap detail tekstur yang ekstrem. Komposisi close-up yang ketat berfokus pada permukaan lukisan.Deskripsi Karya Seni:Lukisan ini dibuat di atas kertas hitam matte bertekstur dalam, menggunakan hanya cat minyak putih murni (pure white impasto). Tidak ada warna lain atau skala abu-abu (grayscale). Cat diaplikasikan dengan sapuan kuas yang sangat tebal, kasar, tidak sempurna, dan ekspresif, serta jejak pisau palet yang menciptakan permukaan relief 3D yang dramatis. Gaya pencahayaan di dalam lukisan adalah chiaroscuro kontras ekstrem—pemisahan tajam antara bentuk cahaya putih tebal dan ruang negatif hitam pekat, tanpa gradien halus. Pencahayaan Rembrandt tunggal memahat wajah dan bentuk subjek, sementara sisi lainnya larut ke dalam kegelapan hitam.Subjek dan Detail:Subjek dalam lukisan mengenakan pakaian elegan, berstruktur, dan kontemporer bergaya minimalis mewah (seperti blazer tajam atau atasan couture berleher tinggi), dirender hanya melalui highlight impasto putih yang berani dan bayangan hitam pekat untuk menekankan bentuk dan lipatan kain. Pose subjek terasa elegan namun dinamis, menangkap ketegangan artistik. Sebuah tanda tangan artis yang halus, ' @kokosima ', dilukis tangan dengan sapuan kuas kursif natural di sudut karya seni, menyatu secara organik ke dalam tekstur cat—terlihat otentik, bukan watermark digital.Pencahayaan Fotografi:Pencahayaan galeri yang dramatis dan terarah (raking light) menyinari permukaan lukisan dari samping, menonjolkan setiap puncak dan lembah dari tekstur impasto yang tebal, menciptakan bayangan mikro yang nyata pada permukaan cat.[Instruksi Khusus Integrasi Wajah Referensi]:Struktur wajah, proporsi, ekspresi, dan identitas subjek yang dilukis HARUS benar-benar identik dengan foto referensi yang disediakan. Dilarang keras mengubah bentuk mata, hidung, bibir, dagu, garis rahang, bentuk kepala, atau gaya rambut. Fitur wajah referensi harus dirender menggunakan teknik impasto putih tebal yang sama, memastikan integrasi organik ke dalam gaya seni yang dramatis ini tanpa kehilangan kemiripan identitas sedikit pun.`
    }
};



